name: Build LibreOffice for Android

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android-libs:
    runs-on: ubuntu-latest
    env:
      ANDROID_NDK: /opt/android-ndk-r25b
      ANDROID_SDK: /opt/android-sdk
      LIBO_ROOT: ${{ github.workspace }}/libreoffice
      ANDROID_ABI: arm64-v8a

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build clang git python3 python3-pip wget unzip

      - name: Download and setup Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -O ndk.zip
          unzip -q ndk.zip -d /opt/
          # NDK zip içinde ekstra klasör varsa düzelt
          if [ -d /opt/android-ndk-r25b/android-ndk-r25b ]; then
            mv /opt/android-ndk-r25b/android-ndk-r25b/* /opt/android-ndk-r25b/
          fi
          ls $ANDROID_NDK  # RELEASE.TXT ve diğer dosyaları kontrol için

      - name: Download and setup Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O sdk.zip
          unzip sdk.zip -d $ANDROID_SDK
          yes | $ANDROID_SDK/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_SDK "platforms;android-21" "build-tools;30.0.3"

      - name: Clone LibreOffice
        run: |
          git clone https://github.com/LibreOffice/core.git $LIBO_ROOT
          cd $LIBO_ROOT
          git checkout master  # Eğer stable branch yoksa master kullan

      - name: Run build script
        run: |
          chmod +x scripts/build-libreoffice.sh
          ./scripts/build-libreoffice.sh

      - name: Copy .so files to repo
        run: |
          mkdir -p android/jniLibs/$ANDROID_ABI
          cp $LIBO_ROOT/instsetoo_native/lib/*.so android/jniLibs/$ANDROID_ABI/
